= Building custom drones

[#hw-compatibility-outdoor]
[#what-sort-of-outdoor-drones-is-skybrush-compatible-with]
== What sort of outdoor drones is Skybrush compatible with?

For outdoor shows, *Skybrush* works with practically any drone that is able to run the open-source https://ardupilot.org[ArduCopter] firmware.
We use a modified version of ArduCopter and we publish the source code of the modified firmware https://github.com/skybrush-io/ardupilot[on Github].
You need to compile and install our modified version on your own drone in order to ensure full compatibility.
We publish pre-compiled versions of the firmware for the most common autopilots, so if your drone uses one of these autopilots, you can simply use our pre-compiled version instead of compiling on your own.

When working with our firmware fork, make sure to check out one of the `+CMCopter-...+` branches with the appropriate upstream ArduPilot version number as the `master` branch simply tracks ArduPilot's `master` branch.

[#hw-compatibility-indoor]
[#what-sort-of-indoor-drones-is-skybrush-compatible-with]
== What sort of indoor drones is Skybrush compatible with?

For indoor shows, *Skybrush* currently supports drones based on the flight controllers of the https://bitcraze.io[Crazyflie] ecosystem, both the "stock" Crazyflie and larger drones based on the Crazyflie Bolt.
We use a modified version of the Crazyflie firmware and we publish its source code https://github.com/skybrush-io/crazyflie-firmware[on Github] as well.
You need to compile and install our modified version on your drone in order to ensure full compatibility.
We publish pre-compiled versions of the firmware for the stock Crazyflie and several suggested Bolt-based builds.

[#if-i-decide-to-build-a-custom-light-show-drone-what-components-are-required]
== If I decide to build a custom light show drone, what components are required?

If you wish to make your drones compatible with Skybrush, contact us to do it together to become trusted partners!
If you wish to try it on your own, these are the basic components needed:

. A <<what-flight-controller-can-i-use-with-skybrush-firmware,flight controller>> running Ardupilot
. A <<what-wifi-module-do-i-need-on-the-drone,WiFi module>> to connect to the ground station running Live
. A GPS receiver - <<should-i-use-rtk-capable-gnss-receivers-for-outdoor-drone-shows,RTK GPS>> is highly recommended
. An <<what-is-an-rc-receiver-and-why-do-i-need-one-on-each-drone,RC receiver>>
. A <<what-kinds-of-light-fixtures-does-skybrush-firmware-support,light fixture>>
. An optional <<what-is-a-sik-radio-and-what-does-it-do,SiK radio>>

[#what-flight-controller-can-i-use-with-skybrush-firmware]
== What flight controller can I use with Skybrush firmware?

You will need a flight controller capable of running Ardupilot firmware that includes a micro SD card slot.
The SD card has a file system where Skybrush stores the show trajectory.
Ardupilot also stores its log files on the SD card.
It is best to purchase a flight controller that has 2MB of internal flash memory to accommodate the Skybrush firmware as it is getting increasingly harder to fit the firmware in smaller 1MB boards.
Boards with 2MB flash also tend to have more RAM, which can be important if you want to drive many NeoPixel LEDs as the signals needed to drive these LEDs need more RAM.

[#what-wifi-module-do-i-need-on-the-drone]
== What WiFi module do I need on the drone?

You will need a WiFi module on your drone (in station mode) to connect to the WiFi router on your ground station.
WiFi is used to upload flight plans (trajectories) to the drone before a show, and to monitor the fleet via MAVLink telemetry.
Most users run our fork of the https://github.com/skybrush-io/mavesp8266[`mavesp8266` firmware] on their WiFi modules.

If you require dual-band Wifi, an ESP32 based module may be used.
Note that our firmware fork and the original `mavesp8266` firmware does not support ESP32 officially yet, but we are working on ESP32 compatibility.

You can also opt for using 4G/5G connectivity with VPN, but then you need a dedicated onboard computer to handle the 4G/5G connection and the VPN itself as the autopilot boards are not equipped for handling VPN connections.

[#should-i-use-rtk-capable-gnss-receivers-for-outdoor-drone-shows]
== Should I use RTK capable GNSS receivers for outdoor drone shows?

RTK capability is not strictly required for drone shows, but it is highly recommended (especially if you want to compete with the bigger players on the market who all use RTK corrections).
The 2-3 m positioning accuracy of regular GNSS receivers can drop down to 1-10 cm using RTK corrections, which increases the accuracy and quality of the show, reduces the required minimal distance between drones and - in case of stable GNSS+RTK reception - increases the overall safety of the system.

Note that when using RTK receivers, you also need an RTK base station or another data source for RTK corrections at the place of the flight.

For testing purposes, it is entirely possible to fly without RTK;
the formations will not be as accurate (especially in the vertical direction) and you need a bit larger safety distance between drones, though.

[#what-is-an-rc-receiver-and-why-do-i-need-one-on-each-drone]
== What is an RC receiver and why do I need one on each drone?

An RC (Remote Control) controller is generally used by RC hobbyists to fly RC models such as fixed-wing aircraft and jets, helicopters, and drones.
The system uses a controller (held by the pilot who uses sticks and switches to fly the model) connected by radio to a receiver on the model.
The Ardupilot documentation describes it https://ardupilot.org/copter/docs/common-rc-systems.html[here].

For show drones, RC control is required for three things:

. To test fly and tune a new or reconfigured drone,
. An RC controller is the Skybrush recommended way to start a drone show, and
. As a secondary or tertiary way to control the drones during emergencies.

One of the challenges of light show drones, is to bind a single RC controller to multiple receivers on the drones.

[#what-kinds-of-light-fixtures-does-skybrush-firmware-support]
== What kinds of light fixtures does Skybrush firmware support?

All drones should be equipped with a strong, bright RGBW LED light or many smaller LEDs distributed all along the body of the drone.
There are multiple options to connect the LEDs;
the easiest is to use three or four PWM outputs of the autopilot to drive the red, green, blue (and optionally the white) channels of the LED, but our firmware also supports driving NeoPixel (WS2812) or ProfiLED LED strips with a single serial line (which means less wiring), and there is also an option for <<is-it-possible-to-use-the-i2c-bus-of-the-flight-controller-to-control-the-leds-on-my-drone,I2C-connected LED modules>>.

[#what-is-a-sik-radio-and-what-does-it-do]
== What is a SiK radio, and what does it do?

The Ardupilot documentation has a great introduction to SiK telemetry radios https://ardupilot.org/copter/docs/common-sik-telemetry-radio.html#:~:text=Overview,patch%20antenna%20on%20the%20ground[here].

Skybrush uses SiK radios as a secondary or tertiary control link to send emergency commands.
It sends commands one-way from the control station to the drone(s) and does not receive telemetry.
https://skybrush.io/modules/sidekick/[Sidekick] software is required (available with a Skybrush licence).

NOTE: SiK radios are not really designed for broadcasting;
they want to "pair" with each other.
Skybrush uses a trick where the duty cycle of each drone radio is pulled down to zero so they are not allowed to transmit.
the GCS radio then _thinks_ that it's all alone (as it hears no traffic from the other radios) and starts sending data into the void.
The drone radio listens to the traffic from the GCS radio and aligns its own transmit / receive cycle to the GCS radio but it will never transmit anything.

[#is-it-possible-to-use-the-i2c-bus-of-the-flight-controller-to-control-the-leds-on-my-drone]
== Is it possible to use the I2C bus of the flight controller to control the LEDs on my drone?

Yes, with our ArduPilot-based firmware fork it is possible.
You need to set the `SHOW_LED0_TYPE` parameter to 7 (I2C RGB) or 11 (I2C RGBW) depending on whether you have RGB or RGBW LEDs, and the `SHOW_LED0_CHAN` parameter to the I2C address that you want to use.
Then, use an Arduino Nano or similar to present your LEDs as an I2C device towards the flight controller.
You can use an Arduino sketch similar to the code snippet below to drive your LEDs;
adjust the pin indices, the number of LEDs and the I2C address accordingly.

[,c]
----
#include <FastLED.h>
#include <Wire.h>

/** GPIO pin used to control the LEDs */
#define LED_CONTROL_PIN 3

/** Number of LEDs controlled by the sketch */
#define LED_COUNT 50

/** Address of the LED controller on the I2C bus */
#define I2C_ADDRESS 42

/** Array storing the current colors of the LEDs */
CRGB colors[LED_COUNT];

void setup() {
  // Change this line depending on the type of LEDs you wish to drive
  // with this sketch. See the FastLED documentation for more details.
  FastLED.addLeds<NEOPIXEL, LED_CONTROL_PIN>(colors, LED_COUNT);

  Wire.begin(I2C_ADDRESS);
  Wire.onReceive(receiveEvent);
}

void loop() {
  delay(100);
}

void receiveEvent(int howMany) {
  int i = 0;
  CRGB color;

  while (Wire.available()) {
    uint8_t incomingByte = Wire.read();
    if (i < 3) {
      color[i++] = incomingByte;
    }
  }

  fill_solid(colors, LED_COUNT, color);
  FastLED.show();
}
----

Note that you will need the FastLED library for the sketch above;
you can install it from the *Tools* / *Manage Libraries...* menu in the Arduino IDE.

[#hw-compatibility-custom-drones]
[#can-you-help-me-in-building-a-drone-compatible-with-skybrush]
== Can you help me in building a drone compatible with Skybrush?

https://collmot.com[CollMot Robotics Ltd.] provides enterprise-grade consultancy services for Skybrush, which also covers the case of building show drones.
Contact us for more details and pricing information, lets cooperate!

[#hw-compatibility-sell-skybrush]
[#can-i-bundle-skybrush-with-the-drones-that-i-sell]
== Can I bundle Skybrush with the drones that I sell?

Yes, you can.
You are allowed to redistribute the pre-compiled binaries for Skybrush components, but note that these pre-compiled binaries may include limitations in the number of drones that the software is willing to handle simultaneously, or other features of the software.
You may also compile Skybrush from its source code, and you are then allowed to redistribute the unrestricted binaries.
However, note that we cannot provide support beyond the standard community support for your customers for free.

Contact us if you would like us to be responsible for supporting your customers in using Skybrush beyond community support as part of our trusted partner program.
