= Running shows

[#number-of-drones]
[#how-many-drones-can-skybrush-handle-at-the-same-time]
== How many drones can Skybrush handle at the same time?

There are no programmatic limits on the number of drones that Skybrush itself can handle, provided that all other components of your operation (laptops, network routers, radio transmitters, chargers, logistics and so on) can also handle the drone count that you have in mind.

A soft limitation occurs when you are using MAVLink-based drones, as their ID stored in the https://ardupilot.org/copter/docs/parameters.html#sysid-thismav-mavlink-system-id-of-this-vehicle[SYSID_THISMAV] parameter can only handle one byte ID-s, so practically you are limited to handle around 250 drones per network.
If you need more than that, you have to use multiple routers in parallel and configure Skybrush Server to access them in different subnets.

Finally, please note that the pre-compiled community version of Skybrush Server is limited to handle max 10 drones.
To enjoy the full extent of Skybrush with unlimited drone number and many other pro features, we encourage you to buy a professional licence.

[#using-skybrush-limitations]
[#are-there-any-built-in-limitations-in-skybrush]
== Are there any built-in limitations in Skybrush?

Binaries (i.e.
pre-compiled versions) of Skybrush that we distribute _may_ have built-in limitations on the number of drones that the software is willing to handle simultaneously, or other features of the software.
The current limitations are always displayed when you start Skybrush Live or Skybrush Server.
You can remove the limitations either by compiling Skybrush on your own from the source code, or by https://skybrush.io/shop/[buying a professional licence] or https://skybrush.io/support/[subscribing to an enterprise support tier], which entitles you to pre-compiled binaries without the limitations, according to contractual terms.

In practice, the limitations we build into pre-compiled versions of Skybrush will not prevent you from evaluating and testing Skybrush with smaller shows;
we only ask you to https://skybrush.io/shop/[purchase a professional licence], to https://skybrush.io/support/[subscribe to enterprise support] or to compile the code on your own if you intend to perform larger projects.

By subscribing to our paid services and products, you are helping us financially in maintaining and developing Skybrush further, and this benefits your own business as well in the long term.

[#do-i-need-active-internet-connection-during-drone-light-shows]
== Do I need active internet connection during drone light shows?

You don't necessarily need active internet connection during drone shows.
You should be connected to the local network of the drones created by your dedicated router to access them from Skybrush Live.
However, there are a few handy features in Skybrush Live that require access to data on the internet, such as the weather widget that attempts to retreive latest Kp-index or any tile server that provides your map tiles.
For what it's worth, you can always buy a 4G mobile wifi dongle and connect it via USB to your laptop to also have internet connection along with your local network connection.
